# Docker Compose for Agent Scholar Streamlit Interface

version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=${API_BASE_URL:-https://your-api-gateway-url.execute-api.region.amazonaws.com/prod}
    volumes:
      # Mount secrets for local development (optional)
      - ./.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Add SSL certificates for HTTPS
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - streamlit
    restart: unless-stopped
    profiles:
      - production