# Streamlit Secrets Configuration
# Replace with your actual API Gateway URL after deployment

API_BASE_URL = "https://your-api-gateway-url.execute-api.region.amazonaws.com/prod"

# Optional: Add authentication tokens or other secrets here
# API_KEY = "your-api-key"
# USER_TOKEN = "your-user-token"